README.md
These are just suggestions; feel free to reject any of the specific diffs!
=> Clarified readme

.travis.yml, xrspatial/__init__.py, xrspatial/classify.py, xrspatial/curvature.py, xrspatial/tests/test_classify.py
=> Add classify methods with Natural breaks and Equal Intervals

README.md
Added documentation to README.md about examples cli commands
=> add docs for examples commands

xrspatial/classify.py, xrspatial/focal.py, xrspatial/pathfinding.py
I removed all global warnings simplefilter settings and replaced it with a context manager at each use. I also tested the edited version that no warning message on import xrspatial. I also tested to generate all warning messages to ensure they still work.
=> Correct warnings

RELEASE.md
This PR solves the issue Add documentation step on release steps #345.
=> add documentation step on release steps

examples/user_guide/4_Focal.ipynb
I did some stylistic edits for the NB to make it a little more user friendly and give it a collaborative tone.
=> Edit Focal user guide

CHANGELOG.md
Fixed the year on the release dates (from 2020 to 2021).
=> fix year on release dates

.github/workflows/pypi-publish.yml
This PR solves the issue #359.
=> add Github Action to publish package to PyPI

docs/source/conf.py, docs/source/releases.json
This PR solves the issue #360.
The new sphinx design will be starting to be used from release 0.1.6.
=> Update docs design version mapping

xrspatial/tiles.py
Tested that it only shows up on import of the tiles module and not base package. @brendancol did you want the warning each time someone calls any of the functions?
=> add deprecation warning to tiles module

CONTRIBUTING.md, README.md
A few typos in README.md and CONTRIBUTING.md, found when reading documentation for the first time.
=> Typos in README.md and CONTRIBUTING.md

CHANGELOG.md
Updated CHANGELOG.md to version 0.1.9.
If this version is not released today we need to change the release date.
=> update changelog v0.1.9

xrspatial/multispectral.py, xrspatial/tests/test_multispectral.py
=> true_color: added output name and attrs

xrspatial/hillshade.py
- lint errors
- use cuda_args to calculate griddim and blockdim
- update example
=> hillshade: linting fixes

xrspatial/proximity.py, xrspatial/tests/test_proximity.py
Addresses issue: https://github.com/microsoft/PlanetaryComputerExamples/issues/79
=> dask case proximity: process whole raster at once if max_distance exceed max possible distance

xrspatial/utils.py
Fixes https://github.com/makepath/xarray-spatial/issues/543
=> Ensure that cupy is not None

xrspatial/classify.py, xrspatial/utils.py, xrspatial/zonal.py
=> validate_arrays: ensure chunksizes of arrays are matching

xrspatial/classify.py
=> natural_breaks: set default value for num_sample

CHANGELOG.md, docs/source/releases.json
Preparation for release v0.3.0
=> Release v0.3.0

.appveyor.yml, .travis.yml, tox.ini
Trying use of python 3.9 on CI.
=> Test python 3.9 on CI

LICENSE.txt, README.md
This needs to be repeated in ~2 weeks time,
=> Change copyright year to include 2021

requirements.txt, xrspatial/aspect.py, xrspatial/classify.py, xrspatial/convolution.py, xrspatial/curvature.py, xrspatial/focal.py, xrspatial/pathfinding.py, xrspatial/tests/general_checks.py, xrspatial/tests/test_aspect.py, xrspatial/tests/test_classify.py, xrspatial/tests/test_curvature.py, xrspatial/utils.py
This PR refactors code, update tests and examples for the following modules:
- aspect
- classify
- focal
Function `general_output_checks()` is added to test that output attributes are preserved.
=> Docs enhancement

xrspatial/aspect.py
=> Aspect: convert to float if int dtype input raster

LICENSE.txt, docs/source/conf.py
Change copyright year to 2022.
=> Change copyright year to 2022

xrspatial/focal.py
=> Focal mean: handle nans inside kernel

benchmarks/benchmarks/aspect.py
This PR adds benchmarking for `aspect()`
=> aspect benchmarks

xrspatial/__main__.py
=> handle CLI errors

benchmarks/asv.conf.json, xrspatial/classify.py, xrspatial/curvature.py, xrspatial/proximity.py, xrspatial/tests/conftest.py, xrspatial/tests/general_checks.py, xrspatial/tests/test_aspect.py, xrspatial/tests/test_classify.py, xrspatial/tests/test_curvature.py, xrspatial/tests/test_focal.py, xrspatial/tests/test_hillshade.py, xrspatial/tests/test_multispectral.py, xrspatial/tests/test_pathfinding.py, xrspatial/tests/test_proximity.py, xrspatial/tests/test_slope.py, xrspatial/tests/test_terrain.py, xrspatial/tests/test_viewshed.py, xrspatial/tests/test_zonal.py, xrspatial/zonal.py
=> Tests improvements

.github/workflows/docs-publish.yml, docs/source/conf.py, xrspatial/aspect.py, xrspatial/classify.py, xrspatial/convolution.py, xrspatial/curvature.py, xrspatial/focal.py, xrspatial/hillshade.py, xrspatial/multispectral.py, xrspatial/proximity.py, xrspatial/slope.py, xrspatial/zonal.py
Improvements to doc build process:
- Change docstring formatting to remove warnings.
- Ensured matplotlib `plot` directive is always available.
- Added `pip list` to doc build github action to assist with debugging.
=> Improvements to doc build process

benchmarks/benchmarks/aspect.py, benchmarks/benchmarks/classify.py, benchmarks/benchmarks/common.py, benchmarks/benchmarks/curvature.py, benchmarks/benchmarks/focal.py, benchmarks/benchmarks/multispectral.py, benchmarks/benchmarks/pathfinding.py, benchmarks/benchmarks/perlin.py, benchmarks/benchmarks/proximity.py, benchmarks/benchmarks/slope.py, benchmarks/benchmarks/terrain.py
This PR refactor existing code in common.py so that we have a base class for benchmarking. It also adds following new benchmarks:
- curvature
- multispectral tools
- classify tools
- focal tools
- proximity tools
- pathfinding a star search
- perlin, terrain generation
=> Add more benchmarks

xrspatial/classify.py, xrspatial/tests/test_classify.py
=> classify tools: classify infinite values as nans, natural_breaks: classify all data points when using sub sample

.github/workflows/codecov.yml, codecov.yml, setup.cfg
Use Codecov to measure the percentage of code covered by the test suite
=> code coverage

xrspatial/viewshed.py
use less calculations in points with same y value
Fixes #
-
-
-
=> Don't calculate angle when not needed

CHANGELOG.md, docs/source/releases.json
=> changelog for release 0.3.3

.github/workflows/docs-publish.yml
Fix doc build dependencies in CI
=> Fix doc build dependencies in CI

xrspatial/focal.py, xrspatial/tests/test_focal.py
=> Focal Hotspots: set unit for output DataArray

examples/user_guide/6_Remote_Sensing.ipynb
Fixes #684
- Fixes the coordinates of the trees layer so they're not inverted
=> Update to remote sensing notebook #684

xrspatial/tests/test_zonal.py, xrspatial/zonal.py
=> 3D numpy zonal_crosstab to support more agg methods

xrspatial/focal.py
Current `hotspots()` cupy case implementation runs on pure cupy. Enabling Numba helps greatly improving the performance. Tested on a data array of size (500, 500) with a kernel size of (5, 5), the result is 6000x faster.
=> Focal hotspots: enable numba.cuda.jit

xrspatial/focal.py, xrspatial/tests/test_focal.py
- disabled validating attrs 
- validating attrs with percent unit
=> updated test hotspots gpu

.github/workflows/test.yml, setup.cfg
Remove support for Python 3.6, add Python 3.10 to CI.
=> Test on python 3.10, remove 3.6

xrspatial/gpu_rtx/mesh_utils.py, xrspatial/gpu_rtx/viewshed.py
Tried to mimic what the CPU does as best as I can
=> Improved viewshed rtx. Now result should match the CPU version

RELEASE.md
Fixes https://github.com/makepath/xarray-spatial/issues/632
=> git log command to get change log

.github/ISSUE_TEMPLATE/feature-proposal.md
- Updated feature-proposal file so appears under issues
=> Fixed feature-proposal.md config

README.md
Fixes #459, #738 
- added Contributors badge
- added Static Analysis badge for python
- reorganized badges into a table
- dropped Contributor list in README.md
=> Update contributor badge

examples/user_guide/3_Zonal.ipynb, examples/user_guide/4_Focal.ipynb, examples/user_guide/6_Remote_Sensing.ipynb
=> More examples to user guide

setup.cfg
Fixes https://github.com/makepath/xarray-spatial/issues/779
=> Pin numpy version

CHANGELOG.md, docs/source/releases.json
Fixes https://github.com/makepath/xarray-spatial/issues/782
=> Change log for release v0.3.7

README.md
Fixes #794
follow-up to #799 and #798
=> Add links to docs to readme
