xrspatial/proximity.py
xrspatial/tests/test_proximity.py

Proximity hot fix_issue44

---

xrspatial/curvature.py
xrspatial/focal.py
xrspatial/tests/test_zonal.py
xrspatial/zonal.py

Xarray-spatial checks if data array data types are a subclass
of numpy.float. However, numpy.float is an alias of
builtins.float, of which only numpy.float64 is subclassed.
Changing numpy.float to numpy.floating allows all numpy float
data types.

Allow all numpy float data types, not just numpy.float64

---

xrspatial/focal.py
xrspatial/tests/test_focal.py

Addresses #125, #124
Using the circle kernel to extend to an annulus kernel. Implementation excludes the cells on the bound of the inner radius of the annulus.
Also implements the ability to return the raw z-scores from `hotspots`.

Add annulus focal kernel

---

xrspatial/focal.py
xrspatial/tests/test_focal.py

Per @thuydotm , simplified some kernel creation.
- Removed `create_kernel()`, now kernels are created by calling their name-specific functions. These are only `circle_kernel()` and `annulus_kernel()` at the moment. Custom kernels are any numpy array and therefore don't have a function, e.g., `kernel = np.ones((3, 3))`.
- Removed `_validate_kernel_shape()` and replaced with `validate_kernel()`, which checks that the kernel is a numpy array and has odd dimensions. This isn't a strict requirement, but I think it makes sense to have the focal point be at the center of a kernel. Perhaps in the future we can accept custom kernels where the focal point is not centered and then pad the kernel in order to center it.
- Updated tests to reflect these changes.

Moved kernel creation to name-specific functions.

---

xrspatial/convolution.py
xrspatial/focal.py
xrspatial/tests/test_focal.py

Addresses #130 
A few things need to be addressed, as mentioned in #130 
- How to handle boundaries. This in an issue on non-symmetrical mean kernels, as their weighted averages can be affected. For my use cases, what is coded works for mean kernels: the values of the raster will be reflected across the boundary so the appropriate weightings are applied (given a symmetrical kernel). Sum kernels don't require padding so `pad=False` works just fine.
- After coding this, there could be some validity in making an easier kernel-creation function to include common functions like weighted means, but it's also very simple to just do `kernel / kernel.sum()` to get this.
- I am a little confused how the original `focal._apply()` behavior was supposed to work from the old `test_apply()`, in one test …

Added convolution module for use in focal statistics.

---

xrspatial/tests/test_zonal.py
xrspatial/zonal.py

add Dask support for zonal_stats and zonal_crosstab

---

xrspatial/hillshade.py

The new code uses less context switching and data transfers, minimizes communication overhead and removes the cupy dependency.  I've made it run by default, if cuda is available. Otherwise if falls back to numpy
This change addresses issue #541

Added a pure numba hillshade that is 10x faster compared to numpy

---

xrspatial/classify.py

Optimized natural break on CPU.
* Removed slow random sample generation with a much faster one.
* Removed a slow and unnecessary nan removal
* Optimized the _run_numpy_jenks_matrices by making it multithreaded.
Initial performance I benchmarked took 11.27s to calculate
New version takes 3.2s

Optimize natural_break on large inputs

---

xrspatial/focal.py
xrspatial/tests/test_aspect.py
xrspatial/tests/test_classify.py
xrspatial/tests/test_curvature.py
xrspatial/tests/test_hillshade.py
xrspatial/tests/test_multispectral.py
xrspatial/tests/test_slope.py
xrspatial/tests/test_zonal.py

Implicit conversion of cupy arrays to numpy, as we do here in test, is no longer allowed. This PR fixes this, and also removes some deprecated uses of `np.float` and `np.int`.

Use explicit cupy to numpy conversion in tests

---

xrspatial/tests/test_zonal.py
xrspatial/zonal.py

This PR uses the same approach as https://github.com/makepath/xarray-spatial/pull/568 to improve performance for zonal stats when input data arrays are dask-backed. It computes stats chunk by chunk and then summarizes all the results and return output as a dask DataFrame. 
This also limits stats that supported in dask case to a subset of default stats, which is safer since a custom statistics would not be always element-wise thus can produce unexpected results.
`nodata_zones` is removed as we already support `zone_ids`, and exclude invalid values (nan, inf) from our calculations.

zonal stats: speed up dask case

---

xrspatial/zonal.py

In dask case zonal stats, the chunksizes of `zones` and `values` should be matching. If not, `values` will be rechunked to be the same as of `zones`.

zonal stats: ensure chunksizes of zones and values are matching

---

setup.py
xrspatial/gpu_rtx/__init__.py
xrspatial/gpu_rtx/cuda_utils.py
xrspatial/gpu_rtx/mesh_utils.py
xrspatial/gpu_rtx/viewshed.py
xrspatial/tests/test_viewshed.py
xrspatial/utils.py
xrspatial/viewshed.py

This PR adds `rtxpy` as an optional dependency and adds the first algorithm that uses it which is gpu viewshed. Also adds some improvements to cpu viewshed.
Added a simple test, more are needed in the long term.
Most of this work was done by @a7az0th, I have just integrated it into `xarray-spatial` and tidied it up a bit.

Add rtx gpu viewshed and improve cpu viewshed

---

xrspatial/zonal.py

stats_dict is not properly populated when zone_values is empty
- moved check of empty zone_values inside the for loop

Error in zonal_stas when zone_values is empty

---

xrspatial/classify.py

Fixes #598.
Bug is caused by code like
```python
max_data = da.nanmax(data[da.isfinite(data)])
```
as lazy evaluation of `data[da.isfinite(data)]` has an unknown `shape`.
The exception that is raised points to a possible solution which is to use `compute_chunk_sizes()` to determine the shape. However, this would be a dask-specific solution.
The solution here keeps the shape of the modified `data` array the same as it was. The same improvement could be applied to the `numpy` and `cupy` implementations, but I have left them for a future PR.

Fix classify bug with dask array

---

setup.py
xrspatial/experimental/__init__.py
xrspatial/experimental/polygonize.py
xrspatial/tests/test_polygonize.py

This PR adds a cpu-based `polygonize` function for numpy-backed `DataArray`s.
The algorithm is slightly different to GDAL's in that it is simpler and has fewer memory reallocations, at the cost of requiring more RAM. It is placed in a new `xrspatial/experimental` directory as the API has not been finalised and in particular there are some optional dependencies (e.g, `geopandas`) that we don't want to be required dependencies.
The API follows that of `rasterio.features.shapes` but there are 4 possible return types that are specified using the `return_type` kwarg. Possibilities are:
* `numpy` (the default) - return polygons as numpy arrays, which is the fastest option.
* `spatialpandas` - return a `spatialpandas.GeoDataFrame`.
* `geopandas` - return a `geopandas.GeoDataFrame`. This option …

polygonize function on cpu for numpy-backed xarray DataArrays

---

README.md
benchmarks/asv.conf.json
benchmarks/benchmarks/polygonize.py

This PR adds a benchmark for the new CPU `polygonize` function, and a table in the `README` showing that that algorithm only supports `numpy` arrays so far.
The benchmark compares our algorithm against `rasterio`'s, which uses `GDAL`.
Timings on my dev machine:
```
====== ============= ============ =============== ============ ====================
--                                         ret                                     
------ ----------------------------------------------------------------------------
nx       numpy      geopandas    spatialpandas    rasterio    rasterio-geopandas 
====== ============= ============ =============== ============ ====================
100    2.23±0.01ms   40.8±0.6ms    9.22±0.07ms    9.97±0.1ms       40.9±0.4ms     
300     21.6±0.2ms    355±4ms …
```

Add benchmark for CPU polygonize

---

xrspatial/classify.py
xrspatial/convolution.py
xrspatial/curvature.py
xrspatial/focal.py
xrspatial/hillshade.py
xrspatial/multispectral.py
xrspatial/perlin.py
xrspatial/slope.py
xrspatial/terrain.py
xrspatial/utils.py
xrspatial/zonal.py

This PR:
- adds a `messages` param to `not_implemented_func()` in order to provide clearer messages in case an array type is not supported for some function.
- refactors code to use ArrayFunctionMapping in following modules/functions: hillshade, true_color, perlin, slope, terrain, zonal

code refactor: use array function mapper, add messages param to not_implemented_func()

---

xrspatial/gpu_rtx/hillshade.py
xrspatial/gpu_rtx/mesh_utils.py
xrspatial/gpu_rtx/viewshed.py
xrspatial/hillshade.py
xrspatial/tests/test_hillshade.py

This PR adds an `rtxpy` implementation of `hillshade` with full shadows. Output looks like this for UK elevation (not very well clipped at sea level but it is only an example):
To use, call `hillshade` with a `cupy`-backed `xarray` and the keyword argument `shadows=True`. The algorithm aims to produce very similar results to the CPU algorithm where there aren't shadows, so follows the usual simple maths of conventional hillshade algorithms.
There are a few improvements to the rtxpy `viewshed` function too, to make it more robust. There is some similar code for both algorithms relating to generation of primary rays; they will be combined later when when I correctly deal with the presence or absence of `x,y` coordinates.
Thanks to @a7az0th who did most of the heavy lifting here.

Add rtx gpu hillshade with shadows

---

xrspatial/convolution.py
xrspatial/curvature.py
xrspatial/focal.py
xrspatial/hillshade.py
xrspatial/slope.py

This PR ensures that an input raster is converted to `float32` if it is originally an integer raster. All functions in `xrspatial` have been run with test data of `int` dtype and the following modules need to be changed:
- convolution.convolution_2d
- curvature
- focal.apply, focal.hotspots
- hillshade
- slope

Convert to float32 if input raster is in int dtype

---

setup.cfg
setup.py

This PR increases the maximum line length allowed by `flake8` from 79 to 100 characters. It fixes the 6th item of issue #626.
Rather than reformatting the whole codebase in one go to take advantage of this, we will instead improve existing code only when we are changing it, or nearby code, in other PRs.

Increase allowed max line length to 100

---

requirements.txt
setup.py

Now that numba 0.55 has been released with support for numpy 1.21 and python 3.10, we no longer need to pin to a max numpy version ourselves.
Fixes issue #565.

Remove numpy version pin

---

.gitignore
MANIFEST.in
pyproject.toml

Clean gitignore and manifest files

---

benchmarks/results.md

Add a .md file to aggregate benchmark results from different devices and OS

Benchmark results

---

CHANGELOG.md
docs/source/releases.json

Preparation for release v0.3.2.

Preparation for release v0.3.2

---

.github/workflows/docs-publish.yml
setup.py

This fixes the recent failure when building the docs in CI. Error was
```
Exception occurred:
File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
```
which can apparently be fixed by pinning the `Jinja2` version to `>=2.11`.

Fix doc build failure due to Jinja2 version

---

xrspatial/analytics.py
xrspatial/tests/general_checks.py
xrspatial/tests/test_analytics.py

Stubbed out function for Analytics module

---

.appveyor.yml
.github/workflows/docs-publish.yml
.github/workflows/pypi-publish.yml
pyproject.toml
requirements-dev.txt
requirements.txt
setup.cfg
setup.py

Fixes #633.
This PR modernises the build system in line with PEP517/518. There is a migration of config data from `setup.py` to `setup.cfg`. I have not been able to remove the two `requirements` files as they are still used by CI. I will deal with these are part of the migration of all of our CI to github actions.
This will most likely break something in the build/release/docs process. Now that we are making regular releases we shall just have to be really careful with the next release.

Modernise build system

---

xrspatial/tests/test_zonal.py
xrspatial/zonal.py

Adds new unit tests and fixes bug related to passing a list of `zone_ids` in the `cupy` implementation of `zonal.stats()` 
- Adds three unit-tests in xrspatial/tests/test_zonal.py that verify the correctness of the cupy implementation of zonal.stats()
- Fixes bug in cupy zonal.stats() (discovered when running the unit-tests)

Pytests for CuPy zonal stats

---

.github/workflows/codecov.yml
codecov.yml
xrspatial/convolution.py
xrspatial/terrain.py
xrspatial/tests/test_analytics.py
xrspatial/tests/test_zonal.py

At the moment Codecov does not capture Numba-jited functions, and GitHub action does not handle cupy/GPU related stuffs. 
- Disable Numba when reporting code coverage, and fix some related issue
- Ignore `xrspatial/experimental` as some tests with `polygonize()` failed when Numba is turned off
- Ignore `xrspatial/gpu_rtx`

Codecov: disable Numba; ignore tests, experimental, and gpu_rtx

---

xrspatial/__init__.py
xrspatial/classify.py
xrspatial/tests/test_classify.py
xrspatial/utils.py

- `binary()`: add docs, support Dask, CuPy

classify: more tests

---

.github/workflows/pypi-publish.yml

This PR fixed the typo in ubuntu version specified in the yaml file that caused issue in publishing the package to pypi.

Fixed ubuntu version in pypi publish

---

benchmarks/benchmarks/common.py
benchmarks/benchmarks/zonal.py
xrspatial/gpu_rtx/__init__.py
xrspatial/hillshade.py
xrspatial/tests/general_checks.py
xrspatial/tests/test_aspect.py
xrspatial/tests/test_classify.py
xrspatial/tests/test_curvature.py
xrspatial/tests/test_focal.py
xrspatial/tests/test_hillshade.py
xrspatial/tests/test_multispectral.py
xrspatial/tests/test_perlin.py
xrspatial/tests/test_slope.py
xrspatial/tests/test_terrain.py
xrspatial/tests/test_zonal.py
xrspatial/utils.py
xrspatial/viewshed.py

This PR makes the identification of cuda and cupy more robust. Previously it was possible to have cuda present but not have cupy installed, and some branches of code would view this as sufficient for running cupy code and hence fail.
The change is to add a new function `has_cuda_and_cupy` that combines the individual `has_cuda` and `has_cupy` functions, which are now made private with underscores. Existing code has been modified to use the new `has_cuda_and_cupy()`, and all new code should use this too.
Also added a `pytest.mark.skipif` decorator called `cuda_and_cupy_available` so we don't have to repeat the `reason` string throughout the code.
I have confirmed that tests run and pass on a cuda-enabled system in the following configurations:
1. No cupy
2. With cupy
3. With cupy and rtxpy

More robust cuda and cupy identification

---

xrspatial/focal.py

When running focal mean with a relatively big data array and `passes` is more than 1, `cudaErrorIllegalAddress` randomly happened, see below example. This caused by the type conversion at each iteration. Only do it once at first pass fixed the issue.
```
[ 50.00%] ··· Running (focal.FocalMean.time_mean--).
[100.00%] ··· focal.FocalMean.time_mean                                                                               1/2 failed
[100.00%] ··· ======= ============ ===========
--           passes / type      
------- ------------------------
nx     1 / cupy    10 / cupy 
======= ============ ===========
10000   37.0±0.4ms     failed  
======= ============ ===========
[100.00%] ···· For parameters: 10000, 10, 'cupy'
Traceback (most recent call last):
File …
```

focal.mean(): only do data type conversion once

---

setup.cfg
xrspatial/tests/test_codebase.py

This PR adds the running of `isort` within `pytest`.
PR #697 removed the linting github action which unintentionally removed the running of `isort` in CI. Here it is added to `test_codebase.py` so that it always runs whenever `pytest` is run. This ensures that `isort` errors are caught before PRs are submitted (assuming PR submitters run `pytest` of course!)

Add isort to pytest

---

xrspatial/curvature.py
xrspatial/focal.py
xrspatial/proximity.py
xrspatial/viewshed.py
xrspatial/zonal.py

In some examples in functions' docstrings, there are some missing imports and typos. Issue https://github.com/makepath/xarray-spatial/issues/701 is an example. This PR fixes the examples in following modules: 
- curvature
- focal
- proximity
- viewshed
- zonal

Correct examples in docstrings

---

xrspatial/classify.py
xrspatial/tests/test_classify.py

The current implementation of natural_breaks algorithm is extremely sequential. The GPU support for this function does not improve but worsen the performance as there is no paralelizable part. It just changes the numpy buffers with cupy buffers without using numba. For these reasons, we should completely remove it.

natural_breaks(): drop gpu support

---

README.md
benchmarks/benchmarks/focal.py
xrspatial/classify.py
xrspatial/focal.py
xrspatial/tests/test_focal.py

Focal apply receives a function as an argument, which seems not supported by numba cuda. On the other hand, it takes in a kernel of size `m*n`. To benefit from the GPU we need to be able to process data cells in parallel, each cell being the center of an `m*n` array. If we want enough flexibility, focal apply needs to allow calculations on an array created from the original data and the kernel, which requires array allocation, which is not supported by numba either. 
For those reasons, we cannot use numba for the cupy case at the moment. The GPU support should be dropped for now.

focal apply: drop gpu support

---

xrspatial/gpu_rtx/mesh_utils.py
xrspatial/gpu_rtx/viewshed.py

Fix for wrong camera ray generation in viewshed. 
While debugging the above issue I noticed that the raster had some sort of scaling applied to the latitude and longitude, but not to the height. I took that scale factor into account while triangulating the terrain and now Hillshade and Viewshed
produce almost identical results compared to their numpy counterparts.
On the first row you have:
the original terrain | numpy viewshed | cupy rtx viewshed
On the second row you have:
the original terrain | numpy hillshade | cupy rtx viewshed with shadows

Fix rtx viewshed rendering blank image

---

examples/housing_price_feature_engineering.ipynb

Add new notebook to discover how geo-related aspects affect housing price in the USA. We will consider a house based on the information provided in an existing dataset with some addtional spatial attributes extracted from its location using xarray-spatial (and probably some elevation dataset, and census-parquet as well?).
We'll first build a machine learning model and train it with all existing features. For each newly added feature, we'll retrain it and compare the results to find out which features help enrich the model.
To be determined:
- What dataset to work on as orignal housing price dataset?
- What are the new features? Slope using an elevation dataset? Population density, ... from Census if none available in the existing features? Proximity distance to nearest hospital / grocery …

WIP Housing price feature engineering notebook

---

xrspatial/tests/general_checks.py
xrspatial/tests/test_zonal.py
xrspatial/zonal.py

Zonal_crosstab 3D: Ensure content of input param `values` is preserved

---

xrspatial/classify.py

Fixes #758
Internally, most of our classification tools call to `_bin()`. In both NumPy and CuPy cases, it classifies data into different bins by looping through all the bins sequentially. This PR makes change to the way we look for correct bin of a value by using binary search.

Classification tools: use binary search in numpy case

---

xrspatial/classify.py
xrspatial/tests/test_classify.py

Fixes #757
To be consistent with all other tools in classify module, this PR changes the way classify.binary() treats NaNs and infinite values. It now considers those values as outliers and classify them as NaNs instead of 0s as of previously.

classify.binary: handle NaNs and infinite values

---

xrspatial/multispectral.py
xrspatial/tests/test_multispectral.py

Multispectral tools: convert data to float32 dtype before doing calculations

---

xrspatial/tests/test_zonal.py

Test all functions to ensure inputs unmodified

---

xrspatial/proximity.py

Fixes https://github.com/makepath/xarray-spatial/issues/775

correct docs for proximity

---

.github/workflows/test.yml
setup.cfg

- Pin datashader version to 0.15.0 and remove numpy version pin.
- Require Python >=3.8.
Xarray-spatial tests were failing due to datashader calling `numpy.warnings`, which is removed in numpy >=1.24.0 ( https://github.com/makepath/xarray-spatial/issues/779 ). Datashader 0.15.0 removes calls to `numpy.warnings` (pr: https://github.com/holoviz/datashader/pull/1176 , changelog: https://github.com/holoviz/datashader/releases/tag/v0.15.0). This pull requests removes the numpy <= 1.23.4 pin in favour of a datashader >= 1.15.0 pin.
Datashader requires Python >=3.8, so this also drops support for Python 3.7.

chore: Remove numpy pin, pin datashader, drop Python 3.7

---

.github/workflows/codecov.yml
.github/workflows/test.yml
README.md
requirements.txt
xrspatial/experimental/polygonize.py

The following PR includes a bunch of fixes that I need to get CI/CD working again.
The most technically unstable is an update to `experimental/polygonize.py` which now has a [custom implementation](https://github.com/numba/numba/issues/8466) of `generated_jit`, but should in the future use `nb.extends.overload` style...
I also:
- got codecov working again
- added Python 3.12 support to CI/CD
- dropped 3.8 / 3.9 support from CI/CD

Bunch of Fixes

---

.readthedocs.yml

Extra requirements need to be `[doc, tests]`, not `[docs, tests]`.
Follow-up to https://github.com/makepath/xarray-spatial/pull/797

Fix typo in readthedocs config

---

.readthedocs.yml
docs/docs-requirements.txt
docs/source/conf.py

Update readthedocs configuration [WIP]

---

CHANGELOG.md
RELEASE.md

- updated changelog for 0.4.0 release
- removed some older doc steps

Prep PR for 0.4.0 Release
